

CREATE OR REPLACE FUNCTION contar_livros_disponiveis(ISBN_LIVRO TEXT)
RETURNS NUMERIC AS $$
DECLARE
    CONTAGEM NUMERIC;
    TOTAL_LIVROS NUMERIC;
    TOTAL_LIVROS_EMPRESTADOS NUMERIC;
BEGIN
    -- Seleciona o total de livros com o ISBN fornecido
    SELECT COUNT(*) INTO TOTAL_LIVROS
    FROM LIVROS 
    WHERE ISBN = ISBN_LIVRO;

    -- Seleciona o total de livros emprestados com o ISBN fornecido
    SELECT COUNT(L.ISBN) INTO TOTAL_LIVROS_EMPRESTADOS
    FROM LIVROS L
    INNER JOIN EMPRESTIMOS EMP ON EMP.LIVRO_ID = L.ID
    WHERE EMP.DATA_DEVOLUCAO IS NULL AND L.ISBN = ISBN_LIVRO;

    -- Calcula a contagem de livros disponíveis
    CONTAGEM := TOTAL_LIVROS - TOTAL_LIVROS_EMPRESTADOS;

    -- Retorna a contagem
    RETURN CONTAGEM;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE VIEW LIVROS_DISPONIVEIS AS
SELECT DISTINCT
	ROW_NUMBER() OVER (order BY ISBN) AS ID,
	NOME,
	ISBN,
	CONTAR_LIVROS_DISPONIVEIS(ISBN) FROM LIVROS
GROUP BY NOME, ISBN;

