INSERT INTO SITUACAORESERVA(ID,DESCRICAO) VALUES(1,'ATENDIDA');
INSERT INTO SITUACAORESERVA(ID,DESCRICAO) VALUES(2,'NÃO ATENDIDA');
INSERT INTO SITUACAORESERVA(ID,DESCRICAO) VALUES(3,'EM ESPERA');
INSERT INTO SITUACAORESERVA(ID,DESCRICAO) VALUES(4,'CANCELADA');
