INSERT INTO SITUACAOSOLICITACAO(ID,DESCRICAO) VALUES(1,'ATENDIDA');
INSERT INTO SITUACAOSOLICITACAO(ID,DESCRICAO) VALUES(2,'NÃO ATENDIDA');
INSERT INTO SITUACAOSOLICITACAO(ID,DESCRICAO) VALUES(3,'EM ESPERA');
INSERT INTO SITUACAOSOLICITACAO(ID,DESCRICAO) VALUES(4,'CANCELADA');
