INSERT INTO SITUACAORESERVA(DESCRICAO) VALUES('ATENDIDA');
INSERT INTO SITUACAORESERVA(DESCRICAO) VALUES('NÃO ATENDIDA');
INSERT INTO SITUACAORESERVA(DESCRICAO) VALUES('EM ESPERA');
INSERT INTO SITUACAORESERVA(DESCRICAO) VALUES('CANCELADA');
